### ISSUE TITLE
[BUG] "expression is not constructable" error

### ISSUE THREAD

**Issue by cwong1900** [JLuboff/connect-mssql-v2#80] opened 2024-11-10 04:52 UTC
**Describe the bug**
This is an issue in TypeScript, not JavaScript. When the package.json file has '"type": "module"', then MSSQLStore is not recognized as a class. Instead, there is an error "error TS2351: This expression is not constructable."

**To Reproduce**
1. Add '"type": "module"' to the package.json.
2. Add code to a ts file.

```
import MSSQLStore from "connect-mssql-v2";
import { config } from "mssql";

function a(c: config) {
    const x = new MSSQLStore(c);
}
```

3. Visual Studio Code shows a red squiggly line under "MSSQLStore" with the error:

error TS2351: This expression is not constructable.
  Type 'typeof import("/Code/node_modules/connect-mssql-v2/dist/src/store")' has no construct signatures.

4. Run tsc and it shows the same error
5. Remove the line '"type": "module"' from package.json and the error disappears.

**Expected behavior**
There should be no errors

**Screenshots**
package.json file
![image](https://github.com/user-attachments/assets/3edb8735-0d49-4905-925f-f45db3df0648)

ts file
![image](https://github.com/user-attachments/assets/59ed3c74-62ad-42d4-8f75-ffa3c6682a99)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version 20.18.0
 - Package Version 5.1.0

**Comment by bradtaniguchi** [comment] 2024-11-18 18:03
This package is setup to support/target commonjs, not ESM modules at this time. 

To support ESM modules, we'd need to have a secondary build step to transpile the project again for ESM and some extra documentation showing both exported modules. I don't believe there is another way to do this, outside of all consumers needing/requiring some of their own extra tooling. 

@JLuboff I'll take a look today (looking into some of my personal git stuff this week).

**Comment by cwong1900** [comment] 2024-11-18 21:04
@bradtaniguchi The following is my tsconfig.json file. In the tsconfig.json created by "tsc --init",  I replaced ""module": "commonjs"" with ""module": "Node16"".

```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "Node16",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

**Comment by bradtaniguchi** [comment] 2024-11-18 22:17
Thanks for getting back with the example. 

I did some testing on myside, and it looks like typescript isn't able to handle this without some tweaking. Luckily in general if your using ESModules, TS/node can handle loading commonjs modules up without a problem. However in this case for whatever reason the `default` export we currently have coming out of our commonjs powered library **isn't picked up correctly** hence the error. 

This can be worked around by leveraging what typescript sees, which is the pre-existing `default` export, which aligns with the MSSQL class you actually need. 

It seems like a quick and dirty (but probably not the only fix) is to do something like:
```
import MSSQLV2 from "connect-mssql-v2";

const { default: MSSQLStore } = MSSQLV2;

// rest of the code is the same
```

This should produce the correct output, where the `default` export is the same class as before. 

I'm unsure if there is a clear/easy fix on our side (maybe named export for the MSSQLStore, so something like `import { MSSQLStore } from 'connect-mssql-v2';` also works, nor am I sure if there is some other TS setting that could be tweaked on the consumer side to get TS to handle this properly. 

Hopefully that at least unblocks, and documents this error for anyone who runs into it in the future. Long-term/perfect world I think having an ESM bundle and a commonjs bundle is the right way to go, but idk if that would ever get done since neither Jeff or me use this library anymore. 

(closing for now, if this workaround doesn't work please re-open, thanks!)

**Closed by bradtaniguchi** 2024-11-18 22:17 UTC
Labels: bug

**Comment by cwong1900** [comment] 2024-11-21 15:32
@bradtaniguchi Your suggestion didn't work. A runtime error occurred. But the following did work.  I changed the 2nd line.

```
import MSSQLV2 from "connect-mssql-v2";

const MSSQLStore = MSSQLV2 as unknown as typeof MSSQLV2.default;
```

**Comment by bradtaniguchi** [comment] 2024-11-21 18:47
Hey thanks for reaching back out with what wasn't working with your setup and providing a tweak to it!

I rechecked mysetup on my side and yea I can confirm I see the same thing, my original test **looked** like it was confirming the import syntax was working, but having an unrelated error, but the error was kicking me out of actually importing the code correctly so I missed it, sorry about that. 

I did a little more digging on how we currently have things setup, I think the changes made for #47 might of caused this current issue. I'm not 100% sure the context for the change made there, or what impact walking that sorta change back could have. 

I'll have to talk with @JLuboff at some point about this one, but in the meantime the workaround you posted above should unblock. 

Thanks again!

**Comment by chladnefazole** [comment] 2024-11-29 08:47
For anyone who comes around later, here's the fix that worked for me:

````
import * as MSSQLStore from 'connect-mssql-v2';

const MSSQLStoreDefault = MSSQLStore as unknown as typeof MSSQLStore.default;

const sqlSessionConfig = {
    user: process.env.DB_USER,
    password: process.env.DB_PWD,
    server: 'localhost',
    database: 'dbname',
    options: {
        encrypt: false,
        trustServerCertificate: true // use this if your MS SQL instance uses a self signed certificate
    }
};
export const SessionStore = new MSSQLStoreDefault(sqlSessionConfig);
````

I just updated the package to v5.1.0 and got this issue. For me this code works for tsc & ts-node-dev.
